name: Docker

on:
  push:
    branches:
      - master
    tags:
      - *
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image: ['aws-sam-cli', 'docker-compose']

    name: Build ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ matrix.image }}
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ matrix.image }}
          path: ${{ matrix.image }}
          push: false
          
  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    strategy:
      fail-fast: false
      matrix:
        image: ['aws-sam-cli', 'docker-compose']

    name: Build and Push ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v2

      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ matrix.image }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_ref: true
          path: ${{ matrix.image }}
