name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ['lambci-ruby-postgres']
    name: Build ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Build ${{ matrix.image }}
        uses: docker/build-push-action@v2
        with:
          pull: true
          context: ${{ matrix.image }}
          push: false
          tags: ${{ github.repository }}/${{ matrix.image }}:latest
          
  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        image: ['lambci-ruby-postgres']
    name: Build and Push ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          pull: true
          tags: ${{ github.repository }}/${{ matrix.image }}:latest
